[project]
name = "hello"
version = "1.0.0"
description = "For saying hello."
authors = [
    { name="Lunethra" }
]
dependencies = [
    "typer[all]",
    "rich",
    "pyfiglet"
]

[project.scripts]
helloto = "helloto.main:app"
